apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-loki-api
  labels:
    k8s-app: sample-loki-api
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: sample-loki-api
  template:
    metadata:
      labels:
        k8s-app: sample-loki-api
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: sample-loki-api
        image: labcabrera/sample-loki-api:latest
        env:
        - name: TZ
          value: Europe/Madrid
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
            name: sampleConfig
            key: LOG_LEVEL
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
            name: sampleConfig
            key: JAVA_OPTS
        - name: FOO
          valueFrom:
            secretKeyRef:
              name: sampleSecret
              key: FOO
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
