apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: sampleConfig
  behavior: create
  literals:
  - java_opts=-Xms512m -Xmx1024m
  - log_level=INFO
secretGenerator:
- name: sampleSecret
  behavior: create
  literals:
  - foo=foosecret
