apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: sampleConfig
  literals:
  - JAVA_OPTS=-Xms512m -Xmx1024m
  - LOG_LEVEL=INFO
secretGenerator:
- name: sampleSecret
  literals:
  - FOO=foosecret
