apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: sampleConfig
  literals:
  - java_opts=-Xms512m -Xmx1024m
secretGenerator:
- name: sampleSecret
  literals:
  - foo=foosecret
  - bar=barsecret