apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-loki-api-cert
spec:
  secretName: sample-loki-api-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: sample-root-ca
    kind: ClusterIssuer
  commonName: sample-loki-api.local
  dnsNames:
    - sample-loki-api.local