apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
spec:
  secretName: argocd-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: sample-root-ca
    kind: ClusterIssuer
  commonName: argocd.local
  dnsNames:
    - argocd.local