spring:
  cloud:
    function:
      definition: processPlayerCreation;processConfirmationOnPlayerCreation
    stream:
      bindings:
        processPlayerCreation-in-0:
          destination: sample.players.creation.v1
          group: players-svc
          contentType: application/json
        processConfirmationOnPlayerCreation-in-0:
          destination: sample.players.created.v1
          group: player-confirmations-svc
          contentType: application/json
        playerCreated-out-0:
          destination: sample.players.created.v1
          contentType: application/json
        playerUpdated-out-0:
          destination: sample.players.updated.v1
          contentType: application/json
        playerDeleted-out-0:
          destination: sample.players.deleted.v1
          contentType: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
          autoCreateTopics: true
          minPartitionCount: 1
        bindings:
          processPlayerCreation-in-0:
            startOffset: earliest
