spring:
  config:
    import:
      - classpath:application-logging.yaml
      - classpath:application-db.yaml
      - classpath:application-cloud-stream.yaml
      - classpath:application-springdoc.yaml
      - classpath:application-security.yaml
  application:
    name: archetype-spring-cloud-stream
  main:
    banner-mode: off

server:
  port: 8082
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,axon
  endpoint:
    health:
      show-details: always

