apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: sample-cicd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: sample-cicd
spec:
  secretName: argocd-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: argocd.local
  dnsNames:
    - argocd.local
  duration: 8760h # 1 año
  renewBefore: 360h # 15 días